services:
  hotnews:
    image: caco/aneiang-pa-news:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aneiang-pa-news
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
