services:
  api:
    build:
      context: .
      dockerfile: Pa.HotNews.Api/Dockerfile
    container_name: pa-hotnews-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production

  web:
    build:
      context: .
      dockerfile: Pa.HotNews.Web/Dockerfile
    container_name: pa-hotnews-web
    depends_on:
      - api
    ports:
      - "5173:80"
